/*
⚠️ Do not edit this file
*/

import {
  connectToDB,
  createDatabase,
  createTable,
  insertData,
  wipeTables
} from './helper';

import speakers from '../db/speakers.json';
import talks from '../db/talks.json';

async function seedDatabase() {
  let conn = await connectToDB();
  await createDatabase(conn, 'jsdays');
  console.log('✏️ - Database created.');
  await createTable(conn, 'jsdays', 'talks');
  await createTable(conn, 'jsdays', 'speakers');
  console.log('✏️ - Tables created.');
  await wipeTables(conn, 'jsdays', ['talks', 'speakers']);
  console.log('💣 - Data has been truncated.');
  await insertData(conn, 'jsdays', 'speakers', speakers);
  await insertData(conn, 'jsdays', 'talks', talks);
  console.log('💾 - Speakers and talks has been uploaded.');
  console.log('🎉 - Work done, enjoy 🍦');
}

seedDatabase();
